// make an enum class for Virtual-Key Codes
// https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

#include <windows.h>

enum class KeyCodes : int {
	// Mouse
	MouseLeft = VK_LBUTTON,
	MouseRight = VK_RBUTTON,
	MouseMiddle = VK_MBUTTON,
	MouseX1 = VK_XBUTTON1,
	MouseX2 = VK_XBUTTON2,

	// Keyboard
	Backspace = VK_BACK,
	Tab = VK_TAB,
	Enter = VK_RETURN,
	Shift = VK_SHIFT,
	Ctrl = VK_CONTROL,
	Alt = VK_MENU,
	Pause = VK_PAUSE,
	CapsLock = VK_CAPITAL,
	Escape = VK_ESCAPE,
	Space = VK_SPACE,
	PageUp = VK_PRIOR,
	PageDown = VK_NEXT,
	End = VK_END,
	Home = VK_HOME,
	Left = VK_LEFT,
	Up = VK_UP,
	Right = VK_RIGHT,
	Down = VK_DOWN,
	Select = VK_SELECT,
	Print = VK_PRINT,
	Execute = VK_EXECUTE,
	PrintScreen = VK_SNAPSHOT,
	Insert = VK_INSERT,
	Delete = VK_DELETE,
	Help = VK_HELP,
	Zero = 0x30,
	One = 0x31,
	Two = 0x32,
	Three = 0x33,
	Four = 0x34,
	Five = 0x35,
	Six = 0x36,
	Seven = 0x37,
	Eight = 0x38,
	Nine = 0x39,
	A = 0x41,
	B = 0x42,
	C = 0x43,
	D = 0x44,
	E = 0x45,
	F = 0x46,
	G = 0x47,
	H = 0x48,
	I = 0x49,
	J = 0x4A,
	K = 0x4B,
	L = 0x4C,
	M = 0x4D,
	N = 0x4E,
	O = 0x4F,
	P = 0x50,
	Q = 0x51,
	R = 0x52,
	S = 0x53,
	T = 0x54,
	U = 0x55,
	V = 0x56,
	W = 0x57,
	X = 0x58,
	Y = 0x59,
	Z = 0x5A,
};

